












#spring.application.name=smartback

#spring.datasource.url=jdbc:postgresql://dpg-d5rkqrbuibrs73coslu0-a.frankfurt-postgres.render.com:5432/smarche
#spring.datasource.username=smarche_user
#spring.datasource.password=dt3RMBr3UuNlZujCVM1ZS1JxjZiBSvkk

#spring.datasource.driver-class-name=org.postgresql.Driver

#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

#server.port=8080

spring.application.name=smartback

# URL: Cambia 'nombre_de_tu_bd' por el nombre real que le pusieras en MariaDB/HeidiSQL
spring.datasource.url=jdbc:mariadb://localhost:3306/marche
spring.datasource.username=root
spring.datasource.password=1221

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# Dialecto para MariaDB
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080